openapi: 3.0.3
info:
  title: hire4recruit API
  description: |
    hire4recruit is a comprehensive recruitment management system that helps organizations streamline their hiring process.
    This API provides endpoints for managing companies, users, jobs, candidates, interviews, and assessments with AI-powered features.

    ## Features
    - Multi-tenant recruitment management
    - AI-powered resume parsing and candidate matching
    - Intelligent interview scheduling
    - Advanced analytics and reporting
    - Razorpay payment integration for subscriptions
    - Role-based permissions and security
    - Email verification for secure account activation

    ## Authentication
    This API uses Bearer token authentication. Include the token in the Authorization header:
    ```
    Authorization: Bearer <your-token>
    ```

    ## Subscription Plans
    - **Basic**: ₹999/month - 10 users, 25 jobs
    - **Professional**: ₹2999/month - 50 users, 100 jobs, AI features
    - **Enterprise**: ₹9999/month - Unlimited users/jobs, full features
  version: 1.0.0
  contact:
    name: hire4recruit API Support
    email: support@hire4recruit.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://api.hire4recruit.com/v1
    description: Production server

tags:
  - name: Health
    description: Health check endpoints
  - name: Authentication
    description: User authentication and authorization
  - name: Companies
    description: Company management
  - name: Users
    description: User management
  - name: Employees
    description: Employee management and team administration
  - name: Roles
    description: Role management and permissions
  - name: Jobs
    description: Job posting and management
  - name: Candidates
    description: Candidate management
  - name: Interviews
    description: Interview scheduling and management
  - name: Assessments
    description: Assessment creation and management

paths:
  # Health endpoints
  /health:
    $ref: './paths/health.yaml#/health'
  /:
    $ref: './paths/health.yaml#/info'

  # Authentication endpoints
  /auth/register-company:
    $ref: './paths/auth.yaml#/register-company'
  /auth/login:
    $ref: './paths/auth.yaml#/login'
  /auth/logout:
    $ref: './paths/auth.yaml#/logout'
  /auth/profile:
    $ref: './paths/auth.yaml#/profile'
  /auth/invite-employee:
    $ref: './paths/auth.yaml#/invite-employee'
  /auth/accept-invitation:
    $ref: './paths/auth.yaml#/accept-invitation'
  /auth/change-password:
    $ref: './paths/auth.yaml#/change-password'
  /auth/forgot-password:
    $ref: './paths/auth.yaml#/forgot-password'
  /auth/reset-password:
    $ref: './paths/auth.yaml#/reset-password'
  /auth/verify-token:
    $ref: './paths/auth.yaml#/verify-token'
  /auth/permissions:
    $ref: './paths/auth.yaml#/permissions'
  /auth/subscription-plans:
    $ref: './paths/auth.yaml#/subscription-plans'
  /auth/retry-payment:
    $ref: './paths/auth.yaml#/retry-payment'
  /auth/verify-payment:
    $ref: './paths/auth.yaml#/verify-payment'
  /auth/verify-email/{userId}:
    $ref: './paths/auth.yaml#/verify-email'

  # Company endpoints
  /companies/profile:
    $ref: './paths/companies.yaml#/profile'
  /companies/stats:
    $ref: './paths/companies.yaml#/stats'
  /companies/users:
    $ref: './paths/companies.yaml#/users'
  /companies/subscription:
    $ref: './paths/companies.yaml#/subscription'
  /companies/subscription/limits:
    $ref: './paths/companies.yaml#/subscription-limits'
  /companies/activity:
    $ref: './paths/companies.yaml#/activity'
  /companies/deactivate:
    $ref: './paths/companies.yaml#/deactivate'
  /companies/reactivate:
    $ref: './paths/companies.yaml#/reactivate'

  # User endpoints
  /users:
    $ref: './paths/users.yaml#/users'

  # Employee endpoints
  /employees:
    $ref: './paths/employees.yaml#/employees'
  /employees/search:
    $ref: './paths/employees.yaml#/employee-search'
  /employees/role/{roleId}:
    $ref: './paths/employees.yaml#/employees-by-role'
  /employees/{employeeId}:
    $ref: './paths/employees.yaml#/employee-by-id'
  /employees/{employeeId}/role:
    $ref: './paths/employees.yaml#/employee-role'
  /employees/{employeeId}/activate:
    $ref: './paths/employees.yaml#/employee-activate'
  /employees/{employeeId}/deactivate:
    $ref: './paths/employees.yaml#/employee-deactivate'
  /employees/{employeeId}/activity:
    $ref: './paths/employees.yaml#/employee-activity'
  /employees/{employeeId}/permissions:
    $ref: './paths/employees.yaml#/employee-permissions'

  # Role endpoints
  /roles:
    $ref: './paths/roles.yaml#/roles'
  /roles/{roleId}:
    $ref: './paths/roles.yaml#/role-by-id'

  # Job endpoints
  /jobs:
    $ref: './paths/jobs.yaml#/jobs'

  # Candidate endpoints
  /candidates:
    $ref: './paths/candidates.yaml#/candidates'
  /candidates/talent-pool:
    $ref: './paths/candidates.yaml#/talent-pool'
  /candidates/search:
    $ref: './paths/candidates.yaml#/search'
  /candidates/{candidateId}:
    $ref: './paths/candidates.yaml#/candidate-by-id'
  /candidates/{candidateId}/status:
    $ref: './paths/candidates.yaml#/update-status'
  /candidates/{candidateId}/resume:
    $ref: './paths/candidates.yaml#/upload-resume'
  /candidates/{candidateId}/summary:
    $ref: './paths/candidates.yaml#/summary'
  /candidates/{candidateId}/applications:
    $ref: './paths/candidates.yaml#/applications'
  /candidates/{candidateId}/applications/{applicationId}:
    $ref: './paths/candidates.yaml#/update-application'
  /candidates/{candidateId}/analytics:
    $ref: './paths/candidates.yaml#/analytics'
  /candidates/{candidateId}/apply:
    $ref: './paths/candidates.yaml#/apply-to-job'

  # Interview endpoints
  /interviews:
    $ref: './paths/interviews.yaml#/interviews'

  # Assessment endpoints
  /assessments:
    $ref: './paths/assessments.yaml#/assessments'

components:
  $ref: './components/index.yaml'

security:
  - BearerAuth: []